Debugging Compose
Debugging compose to track down this network issue.

diff --git a/edgex-docker-compose.yml b/edgex-docker-compose.yml
--- a/edgex-docker-compose.yml
+++ b/edgex-docker-compose.yml
@@ -31,6 +31,85 @@ volumes:
 services:
 
   # ---------------------------------------------------------------------------
+  # Kong Containers -----------------------------------------------------------
+  # ---------------------------------------------------------------------------
+  # 
+  # ---------------------------------------------------------------------------
+
+  kong-db:
+    image: postgres:12.1-alpine
+    networks:
+      edgex-network:
+        aliases:
+            - kong-db
+    ports:
+        - "5432:5432"
+    environment:
+        - 'POSTGRES_DB=kong'
+        - 'POSTGRES_USER=kong'
+        - 'POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
+
+  kong-migrations:
+    image: kong:${KONG_VERSION:-2.0.1}
+    networks:
+      edgex-network:
+        aliases:
+            - kong-migrations
+    environment:
+        - 'KONG_DATABASE=postgres'
+        - 'KONG_PG_HOST=kong-db'
+        - 'KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
+    command: >
+      /bin/sh -cx 
+      'until /consul/scripts/consul-svc-healthy.sh kong-db;
+         do sleep 1;
+      done && kong migrations bootstrap;
+      kong migrations list;
+      code=$$?;
+      if [ $$code -eq 5 ]; then
+        kong migrations up && kong migrations finish;
+      fi'
+    volumes:
+      - consul-scripts:/consul/scripts:ro,z
+    depends_on:
+      - kong-db
+      - volume
+      - consul
+
+  kong:
+    image: kong:${KONG_VERSION:-2.0.1}
+    networks:
+      edgex-network:
+        aliases:
+            - kong
+    ports:
+        - "8000:8000"
+        - "8001:8001"
+        - "8443:8443"
+        - "8444:8444"
+    environment:
+        - 'KONG_DATABASE=postgres'
+        - 'KONG_PG_HOST=kong-db'
+        - 'KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
+        - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
+        - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
+        - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
+        - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
+        - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
+    restart: on-failure
+    command: >
+      /bin/sh -c 
+      "until /consul/scripts/consul-svc-healthy.sh kong-migrations; do sleep 1; done;
+      /docker-entrypoint.sh kong docker-start"
+    volumes:
+      - consul-scripts:/consul/scripts:ro,z
+    depends_on:
+        - kong-db
+        - kong-migrations
+        - volume
+        - consul
+
+  # ---------------------------------------------------------------------------
   # Kuma - Base Image ---------------------------------------------------------
   # ---------------------------------------------------------------------------
   # 
@@ -160,11 +239,11 @@ services:
     image: kuma/kumactl:0.3.2
     volumes: 
       - sidecar-data:/sidecar-data:rw
-      - ./scripts/kuma-installer.sh:/kuma-installer/kuma-installer.sh
+      - ./scripts/kuma-installer.sh:/kuma/kuma-installer.sh
       - ./certs/client:/certs/client
     user: root
     command:
-      - /kuma-installer/kuma-installer.sh
+      - /kuma/kuma-installer.sh
     networks:
       edgex-network: {}
     depends_on:
@@ -349,7 +428,8 @@ services:
     restart: on-failure
 
   logging:
-    image: nexus3.edgexfoundry.org:10004/docker-support-logging-go:master
+    # image: nexus3.edgexfoundry.org:10004/docker-support-logging-go:master
+    image: edgexfoundry/docker-support-logging-go:master-dev
     network_mode: service:logging-namespace
     environment:
       <<: *common-variables
@@ -364,7 +444,7 @@ services:
     image: kuma/kuma-dp:0.3.2
     command:
       - run
-      - --log-level=info
+      - --log-level=debug
     environment:
       - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
       - KUMA_DATAPLANE_MESH=default
@@ -386,47 +466,47 @@ services:
   #
   # ---------------------------------------------------------------------------
 
-  system-namespace:
-    image: busybox:1.31.0
-    command: ["sleep", "infinity"]
-    ports:
-      - "48090:58090"
-    networks:
-      edgex-network:
-        aliases:
-          - edgex-sys-mgmt-agent
-    depends_on:
-      - kuma-control-plane
-    restart: on-failure
+  # system-namespace:
+  #   image: busybox:1.31.0
+  #   command: ["sleep", "infinity"]
+  #   ports:
+  #     - "48090:58090"
+  #   networks:
+  #     edgex-network:
+  #       aliases:
+  #         - edgex-sys-mgmt-agent
+  #   depends_on:
+  #     - kuma-control-plane
+  #   restart: on-failure
 
-  system:
-    image: nexus3.edgexfoundry.org:10004/docker-sys-mgmt-agent-go:master
-    network_mode: service:system-namespace
-    environment:
-      <<: *common-variables
-    volumes:
-      - /var/run/docker.sock:/var/run/docker.sock:z
-    depends_on:
-      - logging
-      - system-namespace
+  # system:
+  #   image: nexus3.edgexfoundry.org:10004/docker-sys-mgmt-agent-go:master
+  #   network_mode: service:system-namespace
+  #   environment:
+  #     <<: *common-variables
+  #   volumes:
+  #     - /var/run/docker.sock:/var/run/docker.sock:z
+  #   depends_on:
+  #     - logging
+  #     - system-namespace
 
-  system-sidecar:
-    image: kuma/kuma-dp:0.3.2
-    command:
-      - run
-      - --log-level=info
-    environment:
-      - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
-      - KUMA_DATAPLANE_MESH=default
-      - KUMA_DATAPLANE_NAME=edgex-sys-mgmt-agent
-      - KUMA_DATAPLANE_ADMIN_PORT=9901
-      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-sys-mgmt-agent/token
-    network_mode: service:system-namespace
-    depends_on:
-      - system-namespace
-    restart: on-failure
-    volumes:
-      - sidecar-data:/sidecar-data
+  # system-sidecar:
+  #   image: kuma/kuma-dp:0.3.2
+  #   command:
+  #     - run
+  #     - --log-level=info
+  #   environment:
+  #     - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
+  #     - KUMA_DATAPLANE_MESH=default
+  #     - KUMA_DATAPLANE_NAME=edgex-sys-mgmt-agent
+  #     - KUMA_DATAPLANE_ADMIN_PORT=9901
+  #     - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-sys-mgmt-agent/token
+  #   network_mode: service:system-namespace
+  #   depends_on:
+  #     - system-namespace
+  #   restart: on-failure
+  #   volumes:
+  #     - sidecar-data:/sidecar-data
 
   # ---------------------------------------------------------------------------
   # EdgeX - Notification Service
@@ -436,46 +516,46 @@ services:
   #
   # ---------------------------------------------------------------------------
   
-  notifications-namespace:
-    image: busybox:1.31.0
-    command: ["sleep", "infinity"]
-    ports:
-      - "48060:58060"
-    networks:
-      edgex-network:
-        aliases:
-          - edgex-support-notifications
-    depends_on:
-      - kuma-control-plane
-    restart: on-failure
+  # notifications-namespace:
+  #   image: busybox:1.31.0
+  #   command: ["sleep", "infinity"]
+  #   ports:
+  #     - "48060:58060"
+  #   networks:
+  #     edgex-network:
+  #       aliases:
+  #         - edgex-support-notifications
+  #   depends_on:
+  #     - kuma-control-plane
+  #   restart: on-failure
 
-  notifications:
-    image: nexus3.edgexfoundry.org:10004/docker-support-notifications-go:master
-    network_mode: service:notifications-namespace
-    environment:
-      <<: *common-variables
-    depends_on:
-      - logging
-      - redis
-      - notifications-namespace
+  # notifications:
+  #   image: nexus3.edgexfoundry.org:10004/docker-support-notifications-go:master
+  #   network_mode: service:notifications-namespace
+  #   environment:
+  #     <<: *common-variables
+  #   depends_on:
+  #     - logging
+  #     - redis
+  #     - notifications-namespace
   
-  notifications-sidecar:
-    image: kuma/kuma-dp:0.3.2
-    command:
-      - run
-      - --log-level=info
-    environment:
-      - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
-      - KUMA_DATAPLANE_MESH=default
-      - KUMA_DATAPLANE_NAME=edgex-support-notifications
-      - KUMA_DATAPLANE_ADMIN_PORT=9901
-      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-support-notifications/token
-    network_mode: service:notifications-namespace
-    depends_on:
-      - notifications-namespace
-    restart: on-failure
-    volumes:
-      - sidecar-data:/sidecar-data
+  # notifications-sidecar:
+  #   image: kuma/kuma-dp:0.3.2
+  #   command:
+  #     - run
+  #     - --log-level=info
+  #   environment:
+  #     - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
+  #     - KUMA_DATAPLANE_MESH=default
+  #     - KUMA_DATAPLANE_NAME=edgex-support-notifications
+  #     - KUMA_DATAPLANE_ADMIN_PORT=9901
+  #     - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-support-notifications/token
+  #   network_mode: service:notifications-namespace
+  #   depends_on:
+  #     - notifications-namespace
+  #   restart: on-failure
+  #   volumes:
+  #     - sidecar-data:/sidecar-data
 
   # ---------------------------------------------------------------------------
   # EdgeX - Metadata Service
@@ -499,7 +579,8 @@ services:
     restart: on-failure
 
   metadata:
-    image: nexus3.edgexfoundry.org:10004/docker-core-metadata-go:master
+    # image: nexus3.edgexfoundry.org:10004/docker-core-metadata-go:master
+    image: edgexfoundry/docker-core-metadata-go:master-dev
     network_mode: service:metadata-namespace
     environment:
       <<: *common-variables
@@ -549,7 +630,8 @@ services:
     restart: on-failure
 
   data:
-    image: nexus3.edgexfoundry.org:10004/docker-core-data-go:master
+    # image: nexus3.edgexfoundry.org:10004/docker-core-data-go:master
+    image: edgexfoundry/docker-core-data-go:master-dev
     network_mode: service:data-namespace
     environment:
       <<: *common-variables
@@ -583,45 +665,45 @@ services:
   #
   # ---------------------------------------------------------------------------
   
-  command-namespace:
-    image: busybox:1.31.0
-    command: ["sleep", "infinity"]
-    ports:
-      - "48082:58082"
-    networks:
-      edgex-network:
-        aliases:
-          - edgex-core-command
-    depends_on:
-      - kuma-control-plane
-    restart: on-failure
+  # command-namespace:
+  #   image: busybox:1.31.0
+  #   command: ["sleep", "infinity"]
+  #   ports:
+  #     - "48082:58082"
+  #   networks:
+  #     edgex-network:
+  #       aliases:
+  #         - edgex-core-command
+  #   depends_on:
+  #     - kuma-control-plane
+  #   restart: on-failure
 
-  command:
-    image: nexus3.edgexfoundry.org:10004/docker-core-command-go:master
-    network_mode: service:data-namespace
-    environment:
-      <<: *common-variables
-    depends_on:
-      - metadata
-      - command-namespace
+  # command:
+  #   image: nexus3.edgexfoundry.org:10004/docker-core-command-go:master
+  #   network_mode: service:data-namespace
+  #   environment:
+  #     <<: *common-variables
+  #   depends_on:
+  #     - metadata
+  #     - command-namespace
     
-  command-sidecar:
-    image: kuma/kuma-dp:0.3.2
-    command:
-      - run
-      - --log-level=info
-    environment:
-      - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
-      - KUMA_DATAPLANE_MESH=default
-      - KUMA_DATAPLANE_NAME=edgex-core-command
-      - KUMA_DATAPLANE_ADMIN_PORT=9901
-      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-core-command/token
-    network_mode: service:command-namespace
-    depends_on:
-      - command-namespace
-    restart: on-failure
-    volumes:
-      - sidecar-data:/sidecar-data
+  # command-sidecar:
+  #   image: kuma/kuma-dp:0.3.2
+  #   command:
+  #     - run
+  #     - --log-level=info
+  #   environment:
+  #     - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
+  #     - KUMA_DATAPLANE_MESH=default
+  #     - KUMA_DATAPLANE_NAME=edgex-core-command
+  #     - KUMA_DATAPLANE_ADMIN_PORT=9901
+  #     - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-core-command/token
+  #   network_mode: service:command-namespace
+  #   depends_on:
+  #     - command-namespace
+  #   restart: on-failure
+  #   volumes:
+  #     - sidecar-data:/sidecar-data
 
   # ---------------------------------------------------------------------------
   # EdgeX - Scheduler Service
@@ -631,47 +713,45 @@ services:
   #
   # ---------------------------------------------------------------------------
   
-  scheduler-namespace:
-    image: busybox:1.31.0
-    command: ["sleep", "infinity"]
-    expose:
-      - "48085"
-    ports:
-      - "48085:58085"
-    networks:
-      edgex-network:
-        aliases:
-          - edgex-support-scheduler
-    depends_on:
-      - kuma-control-plane
-    restart: on-failure
+  # scheduler-namespace:
+  #   image: busybox:1.31.0
+  #   command: ["sleep", "infinity"]
+  #   ports:
+  #     - "48085:58085"
+  #   networks:
+  #     edgex-network:
+  #       aliases:
+  #         - edgex-support-scheduler
+  #   depends_on:
+  #     - kuma-control-plane
+  #   restart: on-failure
 
-  scheduler:
-    image: nexus3.edgexfoundry.org:10004/docker-support-scheduler-go:master
-    network_mode: service:scheduler-namespace
-    environment:
-      <<: *common-variables
-    depends_on:
-      - metadata
-      - scheduler-namespace
+  # scheduler:
+  #   image: nexus3.edgexfoundry.org:10004/docker-support-scheduler-go:master
+  #   network_mode: service:scheduler-namespace
+  #   environment:
+  #     <<: *common-variables
+  #   depends_on:
+  #     - metadata
+  #     - scheduler-namespace
 
-  scheduler-sidecar:
-    image: kuma/kuma-dp:0.3.2
-    command:
-      - run
-      - --log-level=info
-    environment:
-      - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
-      - KUMA_DATAPLANE_MESH=default
-      - KUMA_DATAPLANE_NAME=edgex-support-scheduler
-      - KUMA_DATAPLANE_ADMIN_PORT=9901
-      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-support-scheduler/token
-    network_mode: service:scheduler-namespace
-    depends_on:
-      - scheduler-namespace
-    restart: on-failure
-    volumes:
-      - sidecar-data:/sidecar-data
+  # scheduler-sidecar:
+  #   image: kuma/kuma-dp:0.3.2
+  #   command:
+  #     - run
+  #     - --log-level=info
+  #   environment:
+  #     - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
+  #     - KUMA_DATAPLANE_MESH=default
+  #     - KUMA_DATAPLANE_NAME=edgex-support-scheduler
+  #     - KUMA_DATAPLANE_ADMIN_PORT=9901
+  #     - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-support-scheduler/token
+  #   network_mode: service:scheduler-namespace
+  #   depends_on:
+  #     - scheduler-namespace
+  #   restart: on-failure
+  #   volumes:
+  #     - sidecar-data:/sidecar-data
 
   # ---------------------------------------------------------------------------
   # EdgeX - App Service Rules Service
@@ -737,43 +817,43 @@ services:
   #
   # ---------------------------------------------------------------------------
   
-  rulesengine-namespace:
-    image: busybox:1.31.0
-    command: ["sleep", "infinity"]
-    ports:
-      - "48075:58075"
-    networks:
-      edgex-network:
-        aliases:
-          - edgex-support-rulesengine
-    depends_on:
-      - kuma-control-plane
-    restart: on-failure
+  # rulesengine-namespace:
+  #   image: busybox:1.31.0
+  #   command: ["sleep", "infinity"]
+  #   ports:
+  #     - "48075:58075"
+  #   networks:
+  #     edgex-network:
+  #       aliases:
+  #         - edgex-support-rulesengine
+  #   depends_on:
+  #     - kuma-control-plane
+  #   restart: on-failure
   
-  rulesengine:
-    image: nexus3.edgexfoundry.org:10004/docker-support-rulesengine:master
-    network_mode: service:rulesengine-namespace
-    depends_on:
-      - app-service-rules
-      - rulesengine-namespace
+  # rulesengine:
+  #   image: nexus3.edgexfoundry.org:10004/docker-support-rulesengine:master
+  #   network_mode: service:rulesengine-namespace
+  #   depends_on:
+  #     - app-service-rules
+  #     - rulesengine-namespace
   
-  rulesengine-sidecar:
-    image: kuma/kuma-dp:0.3.2
-    command:
-      - run
-      - --log-level=info
-    environment:
-      - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
-      - KUMA_DATAPLANE_MESH=default
-      - KUMA_DATAPLANE_NAME=edgex-support-rulesengine
-      - KUMA_DATAPLANE_ADMIN_PORT=9901
-      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-support-rulesengine/token
-    network_mode: service:rulesengine-namespace
-    depends_on:
-      - rulesengine-namespace
-    restart: on-failure
-    volumes:
-      - sidecar-data:/sidecar-data
+  # rulesengine-sidecar:
+  #   image: kuma/kuma-dp:0.3.2
+  #   command:
+  #     - run
+  #     - --log-level=info
+  #   environment:
+  #     - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
+  #     - KUMA_DATAPLANE_MESH=default
+  #     - KUMA_DATAPLANE_NAME=edgex-support-rulesengine
+  #     - KUMA_DATAPLANE_ADMIN_PORT=9901
+  #     - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-support-rulesengine/token
+  #   network_mode: service:rulesengine-namespace
+  #   depends_on:
+  #     - rulesengine-namespace
+  #   restart: on-failure
+  #   volumes:
+  #     - sidecar-data:/sidecar-data
 
   # ---------------------------------------------------------------------------
   # EdgeX - Device Virtual Service
@@ -783,44 +863,44 @@ services:
   #
   # ---------------------------------------------------------------------------
 
-  device-virtual-namespace:
-    image: busybox:1.31.0
-    command: ["sleep", "infinity"]
-    ports:
-      - "49990:59990"
-    networks:
-      edgex-network:
-        aliases:
-          - edgex-device-virtual
-    depends_on:
-      - kuma-control-plane
-    restart: on-failure
+  # device-virtual-namespace:
+  #   image: busybox:1.31.0
+  #   command: ["sleep", "infinity"]
+  #   ports:
+  #     - "49990:59990"
+  #   networks:
+  #     edgex-network:
+  #       aliases:
+  #         - edgex-device-virtual
+  #   depends_on:
+  #     - kuma-control-plane
+  #   restart: on-failure
 
-  device-virtual:
-    image: nexus3.edgexfoundry.org:10004/docker-device-virtual-go:master
-    network_mode: service:device-virtual-namespace
-    depends_on:
-      - data
-      - command
-      - device-virtual-namespace
+  # device-virtual:
+  #   image: nexus3.edgexfoundry.org:10004/docker-device-virtual-go:master
+  #   network_mode: service:device-virtual-namespace
+  #   depends_on:
+  #     - data
+  #     - command
+  #     - device-virtual-namespace
   
-  device-virtual-sidecar:
-    image: kuma/kuma-dp:0.3.2
-    command:
-      - run
-      - --log-level=info
-    environment:
-      - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
-      - KUMA_DATAPLANE_MESH=default
-      - KUMA_DATAPLANE_NAME=edgex-device-virtual
-      - KUMA_DATAPLANE_ADMIN_PORT=9901
-      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-device-virtual/token
-    network_mode: service:device-virtual-namespace
-    depends_on:
-      - device-virtual-namespace
-    restart: on-failure
-    volumes:
-      - sidecar-data:/sidecar-data
+  # device-virtual-sidecar:
+  #   image: kuma/kuma-dp:0.3.2
+  #   command:
+  #     - run
+  #     - --log-level=info
+  #   environment:
+  #     - KUMA_CONTROL_PLANE_API_SERVER_URL=http://kuma-control-plane:5681
+  #     - KUMA_DATAPLANE_MESH=default
+  #     - KUMA_DATAPLANE_NAME=edgex-device-virtual
+  #     - KUMA_DATAPLANE_ADMIN_PORT=9901
+  #     - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/sidecar-data/edgex-device-virtual/token
+  #   network_mode: service:device-virtual-namespace
+  #   depends_on:
+  #     - device-virtual-namespace
+  #   restart: on-failure
+  #   volumes:
+  #     - sidecar-data:/sidecar-data
 
 # -----------------------------------------------------------------------------
 # EdgeX - Network Definition
